### ISSUE TITLE
enlargement and colour changes compliance  for math

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/epub-accessibility-tests#62] opened 2023-03-28 20:07 UTC
The Math test book is unclear about the test passing when  AT is not being used. The test should pass if the expression is presented correctly. The test with AT should identify screen reader support. Make it clear that both with and without AT must be conducted.

**Comment by ways2read** [comment] 2023-09-26 15:24
This test should check that when size and colors are changed in the reading system, these are respected in the MathML expressions also.

**Comment by clapierre** [comment] 2024-02-06 16:42
This is a duplicate of #67

**Closed by clapierre** 2024-02-06 16:42 UTC
